version: '3.6'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: es01
    environment:
      #- node.name=es01
      #- cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      #- cluster.initial_master_nodes=es01
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    # ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./stemmer_override.txt:/usr/share/elasticsearch/config/stemmer_override.txt
      - ./synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge