version: '3.6'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: es
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./:/usr/share/elasticsearch/setup
      - ../../fake-api/data/topics/:/usr/share/elasticsearch/topics
    ports:
      - 9200:9200
    networks:
      - elastic
    #command: ./setup/docker-run.sh
    
  deb:
    image: debian:jessie
    container_name: deb
    volumes:
      - ./:/elasticSetup
      - ../../fake-api/data/topics/:/elasticSetup/topics
    networks:
      - elastic
    command: bash ./elasticSetup/docker-run.sh
    #command: tail -F anything
    
volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge