version: "3.7"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    ports:
      - "4444:4444"

  selenium-chrome:
    image: selenium/node-chrome:3.141.59-20200525
    shm_size: "1gb"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium-hub
      - cks-web-app
    environment:
      - TEAMCITY_VERSION
    volumes:
      - ./:/tests
      - /tests/node_modules/

  # CKS dotnet core web app
  cks-web-app:
    build: ../web-app
    container_name: cks-web-app
    depends_on:
      - mock-api
    ports:
      - "8080:8080"
    volumes:
      - ./../web-app/publish:/app
    networks:
      default:
        aliases:
          # Make sure the app uses a nice.org.uk domain so that the cookie banner license works
          - cks-functional-tests.nice.org.uk

  mock-api:
    build: https://github.com/nice-digital/mocks-apis.git#main:search-apis
    container_name: mock-api
    networks:
      default:
        aliases:
          # Pretend to be the test search api endpoint 
          - test-search-api.nice.org.uk

networks:
  default:
    name: cks-functional-tests
