version: "3.7"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    ports:
      - "4444:4444"

  selenium-chrome:
    image: selenium/node-chrome:3.141.59-20200525
    shm_size: "1gb"
    depends_on:	
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  test-runner:
    build: .
    container_name: test-runner
    depends_on:	
      - selenium-hub	
      - cks-web-app
    environment:
      - TEAMCITY_VERSION
    volumes:
      - ./:/tests
      - /tests/node_modules/

  # CKS dotnet core web app
  cks-web-app:
    build: ../web-app
    container_name: cks-web-app
    ports:
      - "8080:8080"
    volumes:
      - ./../web-app/publish:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - ./ElasticSearch/stemmer_override.txt:/usr/share/elasticsearch/config/stemmer_override.txt
      - ./ElasticSearch/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
    ports:
      - 9200:9200
    
  debian:
    build: ./ElasticSearch
    container_name: debian
    volumes:
      - ./ElasticSearch/createAndPopulateIndex.sh:/elasticSetup/createAndPopulateIndex.sh
      - ./ElasticSearch/CKSIndexSettings.json:/elasticSetup/CKSIndexSettings.json
      - ../fake-api/data/topics/:/elasticSetup/topics
    depends_on:
      - elasticsearch
    command: bash ./elasticSetup/createAndPopulateIndex.sh
    #command: tail -F anything
    
networks:
  default:
    name: cks-functional-tests
