/**
 * Best effort dismissal of the EULA banner, which blocks clicks while it's up.
 *
 * Returns quietly when the banner isn't showing, which is the normal case once
 * consent has been given earlier in the same browser session. The old else
 * branch looked up ".SubNav-module--link--24753:nth-child(1)" and paused for
 * 2s: `$()` neither waits nor asserts, so that was a no-op followed by a blind
 * sleep on every page open after the first. The hashed CSS module class is also
 * regenerated by every build, so the selector had long stopped matching.
 */
export async function acceptEULA(): Promise<void> {
	const EULAAcceptButton = await $("#btn-accept-cks-eula");

	if (!(await EULAAcceptButton.isDisplayed())) return;

	await EULAAcceptButton.click();
}
export default acceptEULA;
